# Generated by Django 5.0.2 on 2024-04-18 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Ноинка'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='raiting',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
