# Generated by Django 5.0.2 on 2024-04-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_equipment_is_new_equipment_is_popular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentphotos',
            old_name='equipment',
            new_name='item',
        ),
    ]
