# Generated by Django 5.0.2 on 2024-05-20 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_alter_equipmentfavorites_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='equipments.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL, verbose_name='Пользовател'),
        ),
        migrations.AlterField(
            model_name='equipmentfavorites',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='equipments.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='equipmentphotos',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='equipments.equipment', verbose_name='Оборудование'),
        ),
    ]
