# Generated by Django 5.0.2 on 2024-04-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_new_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='raiting',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
