# Generated by Django 5.0.2 on 2024-04-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_raiting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productphotos',
            old_name='product',
            new_name='item',
        ),
    ]
