# Generated by Django 5.0.2 on 2024-05-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productfavorites_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfavorites',
            options={'managed': True, 'ordering': ['-id'], 'verbose_name': 'Избранные Мёды', 'verbose_name_plural': 'Избранные Мёды'},
        ),
    ]
