# Generated by Django 5.0.2 on 2024-05-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_productfavorites_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compositions',
            options={'verbose_name': 'Состав', 'verbose_name_plural': 'Составы'},
        ),
    ]
