# Generated by Django 5.0.2 on 2024-04-18 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiariesphotos',
            name='apiaries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='apiaries.apiaries'),
        ),
    ]
