# Generated by Django 5.0.2 on 2024-04-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiaries', '0003_remove_apiaries_take_days_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiariesphotos',
            old_name='apiaries',
            new_name='item',
        ),
    ]
