# Generated by Django 5.0.2 on 2024-05-01 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiaries', '0004_rename_apiaries_apiariesphotos_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiariesFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('apiaries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='apiaries.apiaries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiaries_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранные Пасеки',
                'verbose_name_plural': 'Избранные Пасеки',
                'db_table': '',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='apiariesfavorites',
            constraint=models.UniqueConstraint(fields=('apiaries', 'user'), name='unique_apiaries_favorites'),
        ),
        migrations.AlterUniqueTogether(
            name='apiariesfavorites',
            unique_together={('apiaries', 'user')},
        ),
        migrations.AlterIndexTogether(
            name='apiariesfavorites',
            index_together={('apiaries', 'user')},
        ),
    ]
