# Generated by Django 5.0.2 on 2024-05-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiaries', '0005_apiariesfavorites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaries',
            name='radius',
            field=models.CharField(default=1000, help_text='Укажите радиус', max_length=50, verbose_name='Радиус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apiaries',
            name='latitude',
            field=models.CharField(help_text='Укажите северную широту', max_length=50, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='apiaries',
            name='longitude',
            field=models.CharField(help_text='Укажите восточную долготу', max_length=50, verbose_name='Долгота'),
        ),
    ]
