# Generated by Django 5.0.2 on 2024-05-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiaries', '0006_apiaries_radius_alter_apiaries_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiariesfavorites',
            name='apiaries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='apiaries.apiaries', verbose_name='Пасеки'),
        ),
        migrations.AlterField(
            model_name='apiariesphotos',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='apiaries.apiaries', verbose_name='Пасеки'),
        ),
        migrations.AlterField(
            model_name='bookeddays',
            name='apiaries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_days', to='apiaries.apiaries', verbose_name='Пасеки'),
        ),
    ]
