# Generated by Django 5.0.2 on 2024-04-19 12:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiaries', '0003_remove_apiaries_take_days_end_and_more'),
        ('catalog', '0003_product_raiting'),
        ('equipments', '0002_equipment_is_new_equipment_is_popular_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл.почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('adress', models.CharField(max_length=300, verbose_name='Адресс')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderApiaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('quantity', models.PositiveBigIntegerField(default=1, verbose_name='Кол-во')),
                ('apiaries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='apiaries.apiaries')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiaries', to='order.order')),
            ],
            options={
                'verbose_name': 'Товары Заказа Пасеки',
                'verbose_name_plural': 'Товары Заказа Пасеки',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderEqipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('quantity', models.PositiveBigIntegerField(default=1, verbose_name='Кол-во')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='equipments.equipment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='order.order')),
            ],
            options={
                'verbose_name': 'Товары заказа Оборудование',
                'verbose_name_plural': 'Товары заказа Оборудование',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('quantity', models.PositiveBigIntegerField(default=1, verbose_name='Кол-во')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Товары заказа Мед',
                'verbose_name_plural': 'Товары заказа Мед',
                'ordering': ['-id'],
            },
        ),
    ]
