# Generated by Django 5.0.2 on 2024-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderapiaries',
            name='status',
            field=models.CharField(choices=[('in browsing', 'в просмотре'), ('in processing', 'в процессе'), ('Done', 'Получено'), ('Reject', 'ОТКЛОНЕН')], default='in browsing', max_length=30),
        ),
        migrations.AddField(
            model_name='ordereqipments',
            name='status',
            field=models.CharField(choices=[('in browsing', 'в просмотре'), ('in processing', 'в процессе'), ('Done', 'Получено'), ('Reject', 'ОТКЛОНЕН')], default='in browsing', max_length=30),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='status',
            field=models.CharField(choices=[('in browsing', 'в просмотре'), ('in processing', 'в процессе'), ('Done', 'Получено'), ('Reject', 'ОТКЛОНЕН')], default='in browsing', max_length=30),
        ),
    ]
