# Generated by Django 5.0.2 on 2024-04-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderapiaries_status_ordereqipments_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderapiaries',
            old_name='apiaries',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='ordereqipments',
            old_name='equipment',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderproducts',
            old_name='product',
            new_name='item',
        ),
    ]
