# Generated by Django 5.0.2 on 2024-04-19 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiaries', '0004_rename_apiaries_apiariesphotos_item'),
        ('catalog', '0004_rename_product_productphotos_item'),
        ('equipments', '0003_rename_equipment_equipmentphotos_item'),
        ('order', '0004_rename_apiaries_orderapiaries_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('mark', models.PositiveSmallIntegerField(default=1, verbose_name='Оцунка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('apiaries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='equipments.equipment')),
                ('equipments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='apiaries.apiaries')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользовател')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Коментарие',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
