# Generated by Django 5.0.2 on 2024-05-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_itemreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderapiaries',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='orderapiaries',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
