# Generated by Django 5.0.2 on 2024-05-15 08:47

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderapiaries_end_date_orderapiaries_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code_number',
            field=apps.utils.fields.UniqueBigIntegerField(blank=True, default=apps.utils.fields.generate_unique_big_integer, editable=False, null=True, unique=True, verbose_name='Номер заказа'),
        ),
    ]
